### ISSUE TITLE
"should" commands behavior incorrectly in case of failure

### ISSUE THREAD

**Issue by igorstd7** [Project-Quantum/Quantum#16]
"I should see text" and "".*" should exist" cucumber commands in case of failure mark test as failed and throwing "NullPointerException" - while test should be marked as passed. Full output example added.

Steps to reproduce:
1. Create the test which contains "I should see text" or "".*" should exist" command - with unexisting element
2. Run the test
3. See the result
[shouldOutput.txt](https://github.com/Project-Quantum/Quantum/files/631053/shouldOutput.txt)

**Comment by hadasshani** [comment]
This is an open bug in QAF [https://github.com/qmetry/qaf/issues/57](url)

**Comment by hadasshani** [comment]
Should is using verify that suppose to fail the test

**Comment by hadasshani** [comment]
ADd failed steps in the msg error of the report
