### ISSUE TITLE
Support for closing system alerts on mobile

### ISSUE THREAD

**Issue by kontostathisk** [Project-Quantum/Quantum#26]
When you click on a link that takes you to a new tab in iOS. There is a message that lets you click "allow" or "deny". The alert is generated by iOS, so I can't use Selenium to accept the alert.

**Comment by hadasshani** [comment]
You can use switch to NATIVE context, and than work on the native elements. and then return to WEBVIEW context.

You can use DeviceUtils.switchToContext(context) function 
or use available steps like:
I switch to native context
I switch to webview context

**Comment by hadasshani** [comment]
Help needed
