### ISSUE TITLE
Multiple markers at this line - Lexing error on line 47: '%_FEATURE_END_%'. See http://wiki.github.com/cucumber/gherkin/lexingerror for more information. - 46 changed lines

### ISSUE THREAD

**Issue by Nandesh7** [Project-Quantum/Quantum#31]
Hi There, 
Thank you for an awesome documentation and making resources available to make best use of Quantum framework. I imported the training course project & the feature files have common errors as below 

Multiple markers at this line
- Lexing error on line 47: '%_FEATURE_END_%'. See http://wiki.github.com/cucumber/gherkin/lexingerror for more information.
- 46 changed lines

I proof read the feature file webSearch.feature  just the way it got imported & found nothing to be a syntax error. could you please help me know how to address this problem ?

**Comment by kulin24** [comment]
I think you are using Cucumber plugin instead of QAF BDD plugin as described in Wiki link. Can you share the screenshot of this error.

**Comment by Sh169** [comment]
Check with the spaces in the feature file.
Ex: for Scenario check with the colon and for Given, When and Then there shouldn't be colon and more spaces.
