### ISSUE TITLE
Cucumber Scenario Reporting help

### ISSUE THREAD

**Issue by ordd11** [Project-Quantum/Quantum#32]
IntelliJ   2017.1, Cucumber, Quantum Framework, Perfecto Lab (onpremise cloud version   10.3), Perfecto Plugin (version 10.3)
Steps to Reproduce:Run the automation using QAF and Cucumber scenarios on the cloud device.
Description:The reports that in the default execution center are not reflecting the Cucumber Scenarios and there very time-consuming to decipher any useful information. Need a proper reporting format. My tests are grouped by Cucumber scenario names, but the Execution Center Report is showing just the steps across all the scenarios
cloud: http://HCA on premise cloud
Customer want to achieve report categorization in the report with cucumber and QAF (Quantum Kind of framework).

**Comment by kulin24** [comment]
I believe with the new Reportium integration this issue would have been fixed now. 
Do you need any help on this?
