### ISSUE TITLE
Download Report is not creating/downloading pdf for report when user turn on addFullDataToReport=true along with perfecto.download.report both flags enabled.

### ISSUE THREAD

**Issue by rkundaragi** [Project-Quantum/Quantum#46]
1. application properties : have below lines.
addFullDataToReport=true
perfecto.download.reports=true
perfecto.download.summaryReports=true

2. feature files use test data for scenarios which which will have "| recID | recDescription |" parameters which user is required in stesp all test data in each scenario individual report and even test data should be visible for execution reports too.

issue : Download Report is not creating/downloading pdf single report for each test scenarios for each test data's when user turn on addFullDataToReport=true along with perfecto.download.report flags enabled.
i was getting file related exception showing all parameters and showing but it was not able to create PDF file as attached log below : here it could be any test data strings "*#*#*#**#*#**#" or "hhhhmmmmmmhhhhhhhhh", etc.
----------------------------------
[GalaxyS.* 9EB54]: java.io.FileNotFoundException: perfectoReports\9EB54791_Search_Quantum_using_WindTunnel_[{searchResult=*#*#*#**#*#**#,_NetworkSwitch1=4g_lte_good,_recDescription=test2,_searchKey=*#*#*#**#*#**#,_recID=2}]_05232018190349.pdf (The filename, directory name, or volume label syntax is incorrect)
----------------------------------

even i am getting index error as mentioned below logs : 
----------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 88.611 sec <<< FAILURE! - in TestSuite
Search Quantum using WindTunnel(com.qmetry.qaf.automation.step.client.DataDrivenScenario)  Time elapsed: 21.971 sec  <<< FAILURE!
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at com.qmetry.qaf.automation.step.client.DataDrivenScenario.scenario(DataDrivenScenario.java:95)
----------------------------------

**Comment by kulin24** [comment]
Resolved this issue.
