### ISSUE TITLE
java.lang.NullPointerException on PDF Save while running of around 200 testcases from Jenkins

### ISSUE THREAD

**Issue by MrudulaTCS** [Project-Quantum/Quantum#48]
Am running a jenkins job for executing around 700 test cases. I could generate the Execution Summary Report PDF using QAF 1.14 for any number of test cases from my local. But when I tried to execute the same from jenkins , the PDF generation gives an exception of java.lang.NullPointerException for 200-700 cases. It is working fine for lesser number of test cases of 50-80. 

Could you help me on this please. Attaching the screenshots of console for Test Execution of 16 test cases and 118 test cases

![expected](https://user-images.githubusercontent.com/32129383/41223689-68090d4a-6d62-11e8-9b21-7126ddf8cfe9.PNG)
![actual](https://user-images.githubusercontent.com/32129383/41223690-6846565a-6d62-11e8-91fc-69fa22474e92.PNG)

**Comment by kulin24** [comment]
Can you please share your testNG configuration file?
Are you using the latest QUANTUM version?

**Comment by kulin24** [comment]
It might be similar to https://github.com/Project-Quantum/Quantum/issues/49
Please provide the configuration details to reproduce this issue.

**Comment by MrudulaTCS** [comment]
Hi,

Attaching the config file which we are executing in jenkins. 
Am facing that issue only when i trigger the jenkins job to execute the test cases.
We are using 1.14 Quantum Version

[TestngConfigFile.zip](https://github.com/Project-Quantum/Quantum/files/2128472/TestngConfigFile.zip)
