### ISSUE TITLE
Test threads do not initiate in parallel

### ISSUE THREAD

**Issue by davidreedme** [Project-Quantum/Quantum#51]
When configured for a thread count higher than 1, threads are all created immediately; however, tests are started in serial until each completes the first BDD scenario then all tests will continue in parallel until completion. QAF and TestNG do not appear to behave this way. In order to achieve maximum test efficiency, all test threads must commence execution simultaneously.

Example:

&lt;!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd"&gt;
&lt;suite name="Web Demo Suite" verbose="0" parallel="tests" thread-count="5"&gt;
	&lt;listeners&gt;
		&lt;listener class-name="com.quantum.listeners.QuantumReportiumListener" /&gt;
	&lt;/listeners&gt;

	<test name="Web Scenarios Chrome Test 1" enabled="true">
		<parameter name="perfecto.capabilities.platformName" value="Windows"></parameter>
		<parameter name="perfecto.capabilities.platformVersion" value="10"></parameter>
		<parameter name="perfecto.capabilities.browserName" value="Chrome"></parameter>
		<parameter name="perfecto.capabilities.browserVersion" value="64"></parameter>
		<parameter name="perfecto.capabilities.resolution" value="1280x1024"></parameter>
		
		<parameter name="perfecto.capabilities.deviceType" value="Web"></parameter>
		<parameter name="env.resources" value="src/main/resources/common" />
		<groups>
			<run>
				<include name="@Web" />
			</run>
		</groups>
		<classes>
			<class name="com.qmetry.qaf.automation.step.client.gherkin.GherkinScenarioFactory" />
		</classes>
	</test>

	<test name="Web Scenarios Chrome Test 2" enabled="true">
		<parameter name="perfecto.capabilities.platformName" value="Windows"></parameter>
		<parameter name="perfecto.capabilities.platformVersion" value="10"></parameter>
		<parameter name="perfecto.capabilities.browserName" value="Chrome"></parameter>
		<parameter name="perfecto.capabilities.browserVersion" value="65"></parameter>
		<parameter name="perfecto.capabilities.resolution" value="1280x1024"></parameter>
		
		<parameter name="perfecto.capabilities.deviceType" value="Web"></parameter>
		<parameter name="env.resources" value="src/main/resources/common" />
		<groups>
			<run>
				<include name="@Web" />
			</run>
		</groups>
		<classes>
			<class name="com.qmetry.qaf.automation.step.client.gherkin.GherkinScenarioFactory" />
		</classes>
	</test>

	<test name="Web Scenarios Chrome Test 3" enabled="true">
		<parameter name="perfecto.capabilities.platformName" value="Windows"></parameter>
		<parameter name="perfecto.capabilities.platformVersion" value="10"></parameter>
		<parameter name="perfecto.capabilities.browserName" value="Chrome"></parameter>
		<parameter name="perfecto.capabilities.browserVersion" value="66"></parameter>
		<parameter name="perfecto.capabilities.resolution" value="1280x1024"></parameter>
		
		<parameter name="perfecto.capabilities.deviceType" value="Web"></parameter>
		<parameter name="env.resources" value="src/main/resources/common" />
		<groups>
			<run>
				<include name="@Web" />
			</run>
		</groups>
		<classes>
			<class name="com.qmetry.qaf.automation.step.client.gherkin.GherkinScenarioFactory" />
		</classes>
	</test>

	<test name="Web Scenarios Chrome Test 4" enabled="true">
		<parameter name="perfecto.capabilities.platformName" value="Windows"></parameter>
		<parameter name="perfecto.capabilities.platformVersion" value="10"></parameter>
		<parameter name="perfecto.capabilities.browserName" value="Chrome"></parameter>
		<parameter name="perfecto.capabilities.browserVersion" value="67"></parameter>
		<parameter name="perfecto.capabilities.resolution" value="1280x1024"></parameter>
		
		<parameter name="perfecto.capabilities.deviceType" value="Web"></parameter>
		<parameter name="env.resources" value="src/main/resources/common" />
		<groups>
			<run>
				<include name="@Web" />
			</run>
		</groups>
		<classes>
			<class name="com.qmetry.qaf.automation.step.client.gherkin.GherkinScenarioFactory" />
		</classes>
	</test>

	<test name="Web Scenarios Chrome Test 5" enabled="true">
		<parameter name="perfecto.capabilities.platformName" value="Windows"></parameter>
		<parameter name="perfecto.capabilities.platformVersion" value="10"></parameter>
		<parameter name="perfecto.capabilities.browserName" value="Chrome"></parameter>
		<parameter name="perfecto.capabilities.browserVersion" value="68"></parameter>
		<parameter name="perfecto.capabilities.resolution" value="1280x1024"></parameter>
		
		<parameter name="perfecto.capabilities.deviceType" value="Web"></parameter>
		<parameter name="env.resources" value="src/main/resources/common" />
		<groups>
			<run>
				<include name="@Web" />
			</run>
		</groups>
		<classes>
			<class name="com.qmetry.qaf.automation.step.client.gherkin.GherkinScenarioFactory" />
		</classes>

	</test>
&lt;/suite&gt;

**Comment by kulin24** [comment]
FIxed in the last version
