### ISSUE TITLE
Add Check accessibility function

### ISSUE THREAD

**Issue by hadasshani** [Project-Quantum/Quantum#67]
Add support for [checkAccebility](https://developers.perfectomobile.com/pages/viewpage.action?pageId=50922199) function. add Util function and a step.
For more explanation read [here](https://developers.perfectomobile.com/display/PD/Accessibility+testing#expand-Toaccessaccessibilityreports)

**Comment by hadasshani** [comment]
Add download accessibility reports in the ReportUtils downloadAttachments

**Comment by kulin24** [comment]
Added in release 1.22.0
