### ISSUE TITLE
Send collected artifacts of failed tests to the report system

### ISSUE THREAD

**Issue by tal-abraham** [Project-Quantum/Quantum#9]
To enable user to see this information in the report, and later on when jira integration is implemented open a defect directly from the report with this info.
Information which should be added to the report is stack trace,logs, etc - anything relevant that can assist the developer to understand the problem and that exists in the IDE context. This is in addition to the video, snapshot, etc. that should be added to the report from the device.

**Comment by hadasshani** [comment]
implemented in digital zoom
